# Generated by Django 5.0.4 on 2024-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='서버 IP')),
                ('server_port', models.CharField(max_length=32, verbose_name='서버 PORT')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('fail_account_count', models.IntegerField(default=0, verbose_name='서버 연결 실패 횟수')),
                ('server_judge', models.CharField(default='success', max_length=16, verbose_name='잠금 상태')),
            ],
            options={
                'verbose_name': '서버 연결',
                'verbose_name_plural': '서버 연결',
                'db_table': 'server_connection',
            },
        ),
    ]
