# Generated by Django 5.0.4 on 2024-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=32, verbose_name='사용자 아이디')),
                ('useremail', models.EmailField(max_length=32, verbose_name='사용자 이메일')),
                ('userpassword', models.CharField(max_length=32, verbose_name='사용자 비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('fail_account_count', models.IntegerField(default=0, verbose_name='로그인 실패 횟수')),
                ('login_judge', models.CharField(default='success', max_length=16, verbose_name='잠금 상태')),
            ],
            options={
                'verbose_name': '사용자 관리',
                'verbose_name_plural': '사용자 관리',
                'db_table': 'user_management',
            },
        ),
    ]
